services:

  # =========================
  # MySQL - Student Service
  # =========================
  mysql:
    image: mysql:8.0
    container_name: student-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # =========================
  # Address Service (MongoDB Atlas)
  # =========================
  address-service:
    image: harivardhanm/address-details-app:latest
    container_name: address-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local
      MONGO_PASSWORD: Srinurajee1999

  # =========================
  # Student Service
  # =========================
  student-app:
    image: harivardhanm/student-details-app:latest
    container_name: student-details-container
    restart: always
    depends_on:
      - mysql
      - address-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      address-service.url: address-service:8082

volumes:
  mysql-data:
